# Validate this file using http://lint.travis-ci.org/
language: python
sudo: false
python:
  - "2.7"
install:
  - pip install -r tests/requirements.txt
  - pip install -r $VIRTUAL_ENV/src/varda/requirements.txt
  - python setup.py install
script: py.test
